/* do not edit this file! */
// @ts-check
/**
 * lazy image loader
 * @package     GZip Plugin
 * @copyright   Copyright (C) 2005 - 2018 Thierry Bela.
 *
 * dual licensed
 *
 * @license     LGPL v3
 * @license     MIT License
 */
// load responsive css background images
LIB.ready((function(e) {
    // dynamic inline background images
    // or Array.from()
    const t = [].slice.apply(document.querySelectorAll("[data-bg-style]"));
    // responsive css background-image in [style] attribute
        if (t.length > 0) {
        // or use resizeObserver
        const c = t.map((function(e) {
            return JSON.parse(e.dataset.bgStyle);
        }));
        let o = [];
        function n() {
            let n, i, a, r, u, l = o.length;
            for (l = t.length; l--; ) {
                for (i = t[l], a = Object.keys(c[l]), u = e, r = 0; r < a.length && (u = window.matchMedia("(max-width: " + a[r] + "px)"), 
                !u.matches); r++) ;
                if (u == e || !u.matches || r == a.length) continue;
                if (n = "url(" + c[l][a[r]] + ")", i.style.backgroundImage == n) continue;
                let o = new Image, d = function(e) {
                    return function() {
                        i.style.backgroundImage = e;
                    };
                }(n);
                o.src = c[l][a[r]], o.width > 0 && o.height > 0 ? d() : "decode" in o ? o.decode().then(d) : o.onload = d;
            }
        }
        Object.values(c).forEach((function(e) {
            Object.keys(e).forEach((function(e) {
                e = +e, -1 == o.indexOf(e) && o.push(e);
            }));
        })), o.sort((function(e, t) {
            return t - e;
        })), window.addEventListener("resize", n, !1), setTimeout(n, 10);
    }
}));